name: Alpine edge

on: [push]

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    container: alpine:edge

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        env:
          VIVARIUM_PRIV_KEY: ${{ secrets.vivarium_priv_key }}
        run: |
          echo alpine.vivarium.cloud/alpine/edge/main >> /etc/apk/repositories
          echo alpine.vivarium.cloud/alpine/edge/testing >> /etc/apk/repositories
          wget https://alpine.vivarium.cloud/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa.pub
          mv vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa.pub /etc/keys
          apk update && apk add alpine-sdk
          mv abuild.conf /etc
          mkdir -p /var/cache/distfiles && \
          chmod a+w /var/cache/distfiles && \
          adduser --disabled-password vivarium-devel
          addgroup vivarium-devel abuild
          su vivarium-devel
          mkdir /home/vivarium-devel/abuild
          echo VIVARIUM_PRIV_KEY > /home/vivarium-devel/abuild/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa
          echo 'PACKAGER_PRIVKEY="/home/vivarium-devel/.abuild/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa"' > /home/vivarium-devel/abuild/.abuild
      - name: Build Testing
        run: |
          cd testing
          cd unittest++ && abuild checksum && abuild -rF && cd..