name: Alpine edge

on: [push]

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest
    container: alpine:edge

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        env:
          VIVARIUM_PRIV_KEY: ${{ secrets.vivarium_priv_key }}
        run: |
          echo alpine.vivarium.cloud/alpine/edge/main >> /etc/apk/repositories
          echo alpine.vivarium.cloud/alpine/edge/testing >> /etc/apk/repositories
          wget https://alpine.vivarium.cloud/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa.pub
          mv vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa.pub /etc/keys
          apk update && apk add alpine-sdk
          mv abuild.conf /etc
          mkdir -p /var/cache/distfiles && 
          chmod a+w /var/cache/distfiles && 
          mkdir /github/home/.abuild
          echo VIVARIUM_PRIV_KEY > /github/home/.abuild/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa
          echo 'PACKAGER_PRIVKEY="/github/home/.abuild/vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa"' > /github/home/.abuild/abuild.conf
      - name: Build Testing
        run: |
          cd testing
          cd unittest++ && abuild -F checksum && abuild -rF && cd..