name: Alpine v3.11

on: [push]

jobs:
  build:
    name: Build all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: vivarium/abuild@v3.11
        with:
          packager: Luca Cantoreggi <luca@cantoreggi.xyz>
          keyName: vivarium-devel@alpine.vivarium.cloud-5e22f57b.rsa
          privKey: ${{ secrets.vivarium_priv_key }}
          pubKey: ${{ secrets.vivarium_pub_key }}
